### ISSUE TITLE
Uncaught Error: Call to undefined function ssh2_connect() 

### ISSUE THREAD

**Issue by mr-459** [SinaXhpm/php-ssh-brute-force#1]
errore:
:~/php-ssh-brute-force$ php main.php -p=22 -u=root -i=IPs.txt -s=pass.txt
Brute Started ...!
PHP Fatal error:  Uncaught Error: Call to undefined function ssh2_connect() in /home/mr459/php-ssh-brute-force/main.php:47
Stack trace:
#0 {main}
  thrown in /home/mr459/php-ssh-brute-force/main.php on line 47
mr459@mr459:~/php-ssh-brute-force$

**Comment by SinaXhpm** [comment]
u need ssh2 extension !

**Comment by mr-459** [comment]
how to fix that?
i dont know any thing about php
i just want to brute force

**Comment by SinaXhpm** [comment]
it depends on ur os . 
google can help u to install this extension.

**Comment by mr-459** [comment]
ubuntu 18.04lts

**Comment by mr-459** [comment]
solved
